apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello-pod
spec:
  containers:
    - name: hello-pod-container
      image: zcaiobs/primeiro-rep:latest
      ports:
       - containerPort: 8080
